site_name: LogicalQ Documentation
site_author: Georgia Tech Quantum Computing Association
repo_url: https://github.com/GT-Quantum-Computing-Association/LogicalQ

docs_dir: 'docs/docs'
site_dir: 'docs/site'

theme: readthedocs

markdown_extensions:
    - wikilinks
    - toc:
        title: Table of Contents
        permalink: true
    - attr_list
    - fenced_code
    - mdx_math:
        enable_dollar_delimiter: True

plugins:
    - mkdocstrings:
        handlers:
          python:
            paths:
              - LogicalQ/
            selection:
              docstring_style: numpy
    - mkdocs-autoapi:
        autoapi_dir: LogicalQ/
        autoapi_ignore:
          - demos/
          - LogicalQ/**/.ipynb_checkpoints/
    - search

extra_javascript: [
  'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML', 'mathjaxhelper.js',
  'javascript/readthedocs.js'
]

nav:
 - LogicalQ:
    - Overview: index.md

